apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: mkdocs
message: mkdics template
metadata:
  annotations:
    description: Deploys a mkdocs site from a Git repository
    iconClass: "fa fa-newspaper-o"
    openshift.io/display-name: mkdocs
    openshift.io/provider-display-name: CSC
  name: mkdocs
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: mkdocs
    name: mkdocs
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: mkdocs
    name: mkdocs
    namespace: mkdocs
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mkdocs:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_URL}
        ref: ${GIT_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: centos:8
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange
#    - github:
#        secret: ${GITHUB_WEBHOOK_SECRET}
#      type: GitHub
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mkdocs
    name: mkdocs
  spec:
    replicas: 1
    selector:
      app: mkdocs
      deploymentconfig: mkdocs
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: mkdocs
          deploymentconfig: mkdocs
      spec:
        containers:
        - image: ' '
          imagePullPolicy: Always
          name: mkdocs
          ports:
          - containerPort: 8000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mkdocs
        from:
          kind: ImageStreamTag
          name: mkdocs:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mkdocs
    name: mkdocs
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: mkdocs
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: mkdocs
    name: mkdocs
  spec:
    port:
      targetPort: 8000-tcp
    to:
      kind: Service
      name: mkdocs
      weight: 100
    wildcardPolicy: None
parameters:
  - name: GIT_URL
    required: true
    description: "Git URL where the mkdocs document is"
    displayName: Git URL
  - name: GIT_BRANCH
    value: master
    description: "Branch of the repository, by default is master"
    displayName: Branch
